
[ui]
hideTopBar = true

[theme]
# Primary accent for interactive elements
primaryColor = '#15C39A'

# Background color for the main content area
backgroundColor = '#FFFFFF'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#15C39A1A'

# Color used for almost all text
textColor = '#000'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
